#!/bin/tcsh -f

if($# < 1) then
	echo "Usage: compile <problem>"
else
	if ($1 == clean) then
		make clean
	else
		if (-f ./prob.cpp) then
			diff --brief ./problems/$1/prob.cpp ./prob.cpp > ./dump
			if($status) then
				echo "copying prob.cpp"
				cp ./problems/$1/prob.cpp ./prob.cpp
				if (-f ./prob.o) then
					rm ./prob.o
				endif
			endif
		else
			echo "copying prob.cpp"
			cp ./problems/$1/prob.cpp ./prob.cpp
			if (-f ./prob.o) then
				rm ./prob.o
			endif
		endif

		if (-f ./prob.h) then
			diff --brief ./problems/$1/prob.h ./prob.h > ./dump
			if($status) then
				echo "copying prob.h"
				cp ./problems/$1/prob.h ./prob.h
				if (-f ./prob.o) then
					rm ./prob.o
				endif
			endif
		else
			echo "copying prob.h"
			cp ./problems/$1/prob.h ./prob.h
			if (-f ./prob.o) then
				rm ./prob.o
			endif
		endif
		
		if ($# == 2) then
			if ($2 == "debug") then
				echo "making scatter for debugging"
				make debug
			else
				echo "second argument not recognised"
			endif
		else
			echo "making scatter"
			make
		endif
	endif
endif
